### ISSUE TITLE
ceph service bind with specific path issue

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry-incubator/cephfs-bosh-release#4]
I tried with volume **path** like below and the result mount path at container side was same.
Which source should I check?

cf bind-service <your application name> <your volume name> -c {"path": "/data"}

**Comment by marcus-sds** [comment]
When I try with this '{"mount": "/var/vcap/data"}' option , it's working.

**Comment by julian-hj** [comment]
Yes, this is a [known issue](https://github.com/cloudfoundry/volman/blob/master/TROUBLESHOOTING.md#when-the-application-does-not-start) with AUFS.  It will go away when Diego/Garden switches to GrootFS as the standard container file system, but for now, you have to specify a path with a top level folder that already exists.  AUFS is not capable of creating new top level folders.

Having said that, I see that we do not have links to the troubleshooting guide in cephfs-bosh-release, so I will hold off closing this issue until we have fixed the cephfs README

**Comment by julian-hj** [comment]
This should no longer be an issue if you are using the latest version of cloud foundry--cf-deployment now uses GrootFS as the standard.

Also, we have linked troubleshooting instructions into CephFS.  So I am going to go ahead and close this issue.  Please feel free to reopen it or raise new issues if you still have problems.
